name: Golang CI

# on:
#   push:
#     branches:
#       - main
#       - 'feature/**'

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.0
        env:
          GO111MODULE: on

      - name: Run GolangCI-Lint
        run: |
          cd go-app
          golangci-lint run

      - name: Build Docker image
        run: |
          cd go-app
          docker build -t imfuzail/golang-app:latest .
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Push Docker image to Docker Hub
        run: |
          docker push imfuzail/golang-app:latest

      - name: Start Docker Compose services
        run: |
          cd go-app
          docker-compose up -d
