name: NextJs CI

on:
  push:
    paths:
      - 'nextjs-app/**'
  pull_request:
    paths:
      - 'nextjs-app/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd nextjs-app
          npm install

      - name: Run ESLint
        run: |
          cd nextjs-app
          npm run lint

      - name: Build Next.js application
        run: |
          cd nextjs-app
          npm run build

      - name: Run Prettier
        run: |
          cd nextjs-app
          npm run prettier-check

      - name: Build Docker image
        run: |
          cd nextjs-app
          docker build -t imfuzail/nextjs-app:latest .
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Push Docker image to Docker Hub
        run: |
          docker push imfuzail/nextjs-app:latest

      - name: Start Docker Compose services
        run: |
          cd nextjs-app
          docker-compose up -d
